  <!-- SIGN IN MODAL -->
  <?php
require_once(ROOT . 'libs/email/index.php');
  ?>
  
  <div class="modal fade agol-signin" id="signin" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <div class="row">

              <div class="col-md-6">
                <h2 class="text-center">Bienvenido</h2>
                <p class="text-center">IMCOABHER S.A.S</p>
                <img class="w-100" src="<?= RUTAS_APP['ruta_img'] ?>register.jpg" alt="">
                <hr>

                <p class="text-center">¿No tienes una cuenta? ¡Registrate ya!</p>
                <a href="<?= BASE_URL . 'index/registro' ?>">
                  <input type="submit" value="Registrarse" class="btn btn-primary btn-lg lets-go form-control">
                </a>
              </div><!-- /.col-* -->

              <div class="col-md-6">
                <div class="card trans" aria-live="polite">

                  <!-- PUBLIC SIGN IN -->
                  <div class="side-a p-2">
                    <h3>Inicio sesion</h3>
                    <form action="<?= BASE_URL ?>index/ingreso" method="POST">
                      <label class="my-2" for="">Documento</label>
                      <div class="form-group">
                        <select class="form-control" name="tDoc" id="">
                          <option class="form-control" value="CC">CC</option>
                          <option class="form-control" value="CE">CE</option>
                          <option class="form-control" value="TI">TI</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="InputEmailPublic">Numero de Doc.</label>
                        <input type="number" name="nDoc" class="form-control" id="InputEmailPublic" placeholder="Numero de documento">
                      </div>

                      <div class="form-group">
                        <label for="InputPasswordPublic">Contraseña</label>
                        <input type="password" name="pass" class="form-control" id="InputPasswordPublic" placeholder="Contraseña">
                      </div>


                      <div class="checkbox">
                        <label>
                          <input type="checkbox"> Recordar mi contraseña
                        </label>
                      </div>
                      <input type="submit" name="btnLogin" value="Enviar" class="btn btn-primary btn-lg lets-go form-control">
                    </form>


                    <hr>
                    <form action="" method="post">


                    <p class="text-center "> <button type="submit" class=" text-dark btn forms_buttons-forgot">¿Olvidó la contraseña?</button>
                    <input type="hidden" name="enviar">
                    </form>

                    </p>
                  </div><!-- /.side-a -->

                  <!-- ENTERPRISE SIGN IN -->

                </div><!-- /.card -->

              </div><!-- /.col-* -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div><!-- /.modal-body -->
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->